import { PohangPlace } from '@/types/poing';

export const POHANG_MOCK_PLACES: PohangPlace[] = [
  {
    id: 'homigot',
    title: '호미곶 해맞이광장',
    category: '바다',
    address: '경상북도 포항시 남구 호미곶면 해맞이로 150',
    mapx: 129.5707,
    mapy: 36.0792,
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    description: '한반도 동쪽 끝, 상생의 손 구조물과 웅장한 동해 일출을 감상할 수 있는 포항 대표 랜드마크',
    recommendedDurationMinutes: 60,
    bestTimeOfDay: '아침',
    visitorRankTopPercent: 3,
    congestionLevel: '보통',
    relatedPlaceIds: ['guryongpo', 'homi_coastal_walk'],
    recommendationReason: '포항 방문자 수 상위 3% 스팟이며, 일출/아침 시간대 감상 시 최고의 만족도를 보입니다.'
  },
  {
    id: 'spacewalk',
    title: '환호공원 스페이스워크',
    category: '산책/공원',
    address: '경상북도 포항시 북구 환호공원길 30',
    mapx: 129.3822,
    mapy: 36.0645,
    imageUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80',
    description: '구름 위를 걷는 듯한 짜릿함을 선물하는 국내 최대 규모의 체험형 쇠제 스페이스 트랙 랜드마크',
    recommendedDurationMinutes: 90,
    bestTimeOfDay: '점심',
    visitorRankTopPercent: 1,
    congestionLevel: '혼잡',
    relatedPlaceIds: ['hwanho_art', 'yeongildae'],
    recommendationReason: '포항 검색량 1위의 킬러 스팟으로 영일대 해수욕장과 연관 동선 바인딩률이 82%에 달합니다.'
  },
  {
    id: 'yeongildae',
    title: '영일대 해수욕장 & 해상누각',
    category: '바다',
    address: '경상북도 포항시 북구 해안로 191',
    mapx: 129.3789,
    mapy: 36.0560,
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    description: '도심 속 아름다운 해변과 바다 위에 떠 있는 우리나라 최초의 해상 누각 영일정이 매력적인 장소',
    recommendedDurationMinutes: 60,
    bestTimeOfDay: '야경',
    visitorRankTopPercent: 2,
    congestionLevel: '보통',
    relatedPlaceIds: ['spacewalk', 'yeonam_cafe'],
    recommendationReason: '야경 연관 관광지 지수가 매우 높아 저녁 타임에 방문 시 포쇄 야경 조망에 최적입니다.'
  },
  {
    id: 'jukdo_market',
    title: '죽도시장 (식도락 탐방)',
    category: '시장/식도락',
    address: '경상북도 포항시 북구 죽도시장4길 13-12',
    mapx: 129.3662,
    mapy: 36.0361,
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    description: '동해안 최대 규모의 전통시장. 싱싱한 포항 물회, 대게, 수산물과 다양한 장터 먹거리가 가득한 곳',
    recommendedDurationMinutes: 90,
    bestTimeOfDay: '점심',
    visitorRankTopPercent: 2,
    congestionLevel: '보통',
    relatedPlaceIds: ['pohang_canal', 'yeongildae'],
    recommendationReason: '점심시간대 방문자 집중률이 높아 식도락 동선 필수 코스로 바인딩되었습니다.'
  },
  {
    id: 'guryongpo',
    title: '구룡포 근대문화역사거리',
    category: '문화/야경',
    address: '경상북도 포항시 남구 구룡포읍 구룡포길 153-1',
    mapx: 129.5591,
    mapy: 35.9892,
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    description: '드라마 <동백꽃 필 무렵> 촬영지로 유명하며 100여 년 전 근대 가옥이 보존된 감성 문화거리',
    recommendedDurationMinutes: 75,
    bestTimeOfDay: '점심',
    visitorRankTopPercent: 4,
    congestionLevel: '여유',
    relatedPlaceIds: ['homigot', 'guryongpo_park'],
    recommendationReason: '호미곶 동선과 연속 방문률이 76%로 높은 연관 스팟입니다.'
  },
  {
    id: 'igari',
    title: '이가리 뼛전망대',
    category: '바다',
    address: '경상북도 포항시 북구 청하면 이가리 산67-3',
    mapx: 129.3941,
    mapy: 36.1832,
    imageUrl: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=800&q=80',
    description: '독도를 향해 길게 뻗은 빨간 지붕의 뼛모양 해상 전망대로 푸른 동해바다 뷰가 인상적인 스팟',
    recommendedDurationMinutes: 45,
    bestTimeOfDay: '노을/저녁',
    visitorRankTopPercent: 5,
    congestionLevel: '여유',
    relatedPlaceIds: ['bogyeongsa', 'yeongildae'],
    recommendationReason: '현재 혼잡도 [여유] 상태로 쾌적하게 동해 바다 뷰 사진을 찍기 좋은 드라이브 코스입니다.'
  }
];
